apiVersion: v1
kind: Service
metadata:
  name: simpleweb0-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: simpleweb-rs
  type: NodePort
  sessionAffinity: ClientIP
